const Images = [
    {
        tag: ["9Lana", "2D", "BALALAIKA", "Girl", "Doll", "Music"],
        author: "DENN",
        imageUrl: "https://pbs.twimg.com/media/GHBBZuObwAEiiDD?format=jpg&name=4096x4096",
        image: "",
        description: "BALALAIKA: https://youtu.be/S2Xu6_XWy4M?si=kI-B_kIIszn_AuLl",
    },
    {
        tag: ["9Lana", "2D", "CHINCHIRO-RHYTHM", "Girl", "Doll", "Music"],
        author: "DENN",
        imageUrl: "https://pbs.twimg.com/media/GakRwN5awAAwhwP?format=jpg&name=4096x4096",
        image: "",
        description: "CHINCHIRO-RHYTHM: https://youtu.be/RqK3bGxeH98?si=--OZ-8FIJU-wO2Pn",
    },
    {
        tag: ["9Lana", "2D", "1st anniversary", "Girl", "Doll", "Music"],
        author: "DENN",
        imageUrl: "https://pbs.twimg.com/media/Go490jlbAAA6GgF?format=jpg&name=large",
        image: "",
        description: "",
    },
    {
        tag: ["9Lana", "2D", "Youtube Music Weekend", "Key visual", "Girl", "Doll", "Music"],
        author: "DENN",
        imageUrl: "https://pbs.twimg.com/media/GzbYglWasAAaKNY?format=jpg&name=large",
        image: "",
        description: "",
    },
    {
        tag: ["9Lana", "2D", "NINE TAILS", "Girl", "Doll", "Music"],
        author: "DENN",
        imageUrl: "https://pbs.twimg.com/media/GzwC1ESaQAAVm6o?format=jpg&name=4096x4096",
        image: "",
        description: "NINE TAILS: https://youtu.be/l70B7oRYKoo?si=wOdljwZoKkFIBhbZ",
    },
    {
        tag: ["9Lana", "2D", "NINE TAILS", "Girl", "Doll", "Music"],
        author: "DENN",
        imageUrl: "https://pbs.twimg.com/media/GzwC1EUagAAMO35?format=jpg&name=4096x4096",
        image: "",
        description: "NINE TAILS: https://youtu.be/l70B7oRYKoo?si=wOdljwZoKkFIBhbZ",
    },
    {
        tag: ["9Lana", "2D", "NINE TAILS", "Girl", "Doll", "Music"],
        author: "DENN",
        imageUrl: "https://pbs.twimg.com/media/GzwhEOuaAAEZfc8?format=jpg&name=4096x4096",
        image: "",
        description: "NINE TAILS: https://youtu.be/l70B7oRYKoo?si=wOdljwZoKkFIBhbZ",
    },
    {
        tag: ["Ellen", "2D", "Girl", "ZZZ", "Game", "Gacha", "Shark", "Thiren", "Winter"],
        author: "Jiwoo",
        imageUrl: "https://pbs.twimg.com/media/GfnCOeub0AA5pZB?format=jpg&name=medium",
        image: "",
        description: "Ellen on a snowy winter night",
    },
    {
        tag: ["Ellen", "2D", "Girl", "ZZZ", "Game", "Gacha", "Shark", "Thiren", "Summer"],
        author: "Jiwoo",
        imageUrl: "https://pbs.twimg.com/media/GgdUlA5a8AAuB8W?format=jpg&name=4096x4096",
        image: "",
        description: "Ellen eating an ice cream inside a station",
    },
    {
        tag: ["Ellen", "2D", "Girl", "ZZZ", "Game", "Gacha", "Shark", "Thiren", "Summer"],
        author: "Jiwoo",
        imageUrl: "https://pbs.twimg.com/media/GgdlaTza8AEMdVQ?format=jpg&name=4096x4096",
        image: "",
        description: "Ellen taking a selfie eating an ice cream",
    },
    {
        tag: ["Ellen", "2D", "Girl", "ZZZ", "Game", "Gacha", "Shark", "Thiren", "Summer"],
        author: "Jiwoo",
        imageUrl: "https://pbs.twimg.com/media/Gkop8EtbkAMIA4U?format=jpg&name=4096x4096",
        image: "",
        description: "Ellen taking a picture of a hollow",
    },
    {
        tag: ["Ellen", "2D", "Girl", "ZZZ", "Game", "Gacha", "Shark", "Thiren", "Summer"],
        author: "Jiwoo",
        imageUrl: "https://pbs.twimg.com/media/GgdlgzlaMAAju1X?format=jpg&name=4096x4096",
        image: "",
        description: "Ellen listening to music",
    },
];

export default Images;